name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/**.md'

jobs:
  Build (x64):
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore -r win-x64
  Build (ARM64):
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore -r win-arm64
