name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/**.md'
      - '**TEMPLATE**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/**.md'
      - '**TEMPLATE**'

jobs:
  amd64build:
    name: 'Build (x64)'
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore -r win-x64
  arm64build:
    name: 'Build (ARM64)'
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore dependencies
      run: |
        cd src
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --no-restore -r win-arm64
